# The URL the site will be built for
base_url = "https://creusot.rs"

title = "Creusot"
description = "Formal verification tool for Rust"

[markdown]

[markdown.highlighting]
style = "class"
light_theme = "one-light"
dark_theme = "catppuccin-mocha"
extra_grammars = ["grammars/rust.json", "grammars/pearlite.json"]

[extra]
favicon = true
logo = "creusot-logo.jpg"
version = "0.10.0"
